# Generated by Django 5.2 on 2025-05-27 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('tool', models.CharField(choices=[('nmap', 'NMAP'), ('nikto', 'NIKTO')], max_length=10)),
                ('scan_type', models.CharField(max_length=50)),
                ('result', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('low_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
