# Generated by Django 5.2 on 2025-04-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('tool', models.CharField(choices=[('nmap', 'NMAP'), ('nikto', 'NIKTO')], max_length=10)),
                ('scan_type', models.CharField(max_length=50)),
                ('result', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('low_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
            ],
        ),
    ]
